services:
  ebook_converter_bot:
    container_name: ebook_converter_bot
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: ["/opt/venv/bin/python", "-m", "ebook_converter_bot"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - PDF_EXTRA_FONTS_DIR=/data/pdf-fonts
    security_opt:
      - seccomp=/etc/docker/seccomp-profile-v0.2.1.json
    restart: unless-stopped
    volumes:
      - "./:/app"
      - "./extra-pdf-fonts:/data/pdf-fonts:ro"
      - /etc/localtime:/etc/localtime:ro
