[tool.poetry]
name = "ebook-converter-bot"
version = "0.1.0"
description = "Telegram Bot for covnerting E-Books"
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Telethon = "^1.28.5"
cryptg = "^0.4"
aiohttp = {extras = ["fast"], version = "^3.8.4"}
hachoir = "^3.2.0"
sqlalchemy = "^2.0.14"
EbookLib = "^0.18"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^5.0.4"
isort = "^5.11.5"
mypy = "^1.3"
pre-commit = "^2.21.0"
pycln = "^2.1.3"
types-toml = "^0.10.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
include = '(\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | data/locales
  | \.venv
)/
'''

[tool.isort]
profile = "black"

[tool.mypy]
files = ["ebook_converter_bot"]
ignore_missing_imports = true
disallow_untyped_defs = true
#disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

[tool.pycln]
all = true
