[tool.poetry]
name = "ebook-converter-bot"
version = "0.1.0"
description = "Telegram Bot for covnerting E-Books"
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Telethon = "^1.24.0"
cryptg = "^0.3"
aiohttp = {extras = ["fast"], version = "^3.8.1"}
hachoir = "^3.1.3"
sqlalchemy = "^1.4.39"
EbookLib = "^0.17.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
