[tool.poetry]
name = "ebook-converter-bot"
version = "0.1.0"
description = "Telegram Bot for covnerting E-Books"
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Telethon = "^1.25.2"
cryptg = "^0.3"
aiohttp = {extras = ["fast"], version = "^3.8.3"}
hachoir = "^3.1.3"
sqlalchemy = "^1.4.41"
EbookLib = "^0.17.1"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.971"
pre-commit = "^2.20.0"
pycln = "^2.1.1"
types-toml = "^0.10.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
include = '(\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | data/locales
  | \.venv
)/
'''

[tool.isort]
profile = "black"

[tool.mypy]
files = ["ebook_converter_bot"]
ignore_missing_imports = true
disallow_untyped_defs = true
#disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

[tool.pycln]
all = true
